odl/discr/discr_ops.py, test/discr/discr_ops_test.py
In response to issue #131, should be OK.
@moosmann?
=> Issue 131  forward diff

odl/trafos/wavelet.py, test/trafos/wavelet_test.py
Implement 1D wavelet transforms, update the helper functions and the tests accordingly. 
Removed redundant inputs from 3D helper functions.
=> Issue155  1dwavelet transform

odl/trafos/wavelet.py
Made the improvements of the docstrings and the fix of linearity check.
=>  Improve wavelet transform #166 

odl/util/phantom.py
Trivial PR, just adding a nice new phantom.
=> 'Submarine' phantom

examples/tomo/xray_trafo.py, odl/solvers/util/partial.py, odl/tomo/__init__.py, odl/tomo/backends/astra_cpu.py, odl/tomo/backends/astra_setup.py, odl/tomo/geometry/conebeam.py, odl/tomo/geometry/detector.py, odl/tomo/geometry/fanbeam.py, odl/tomo/geometry/geometry.py, odl/tomo/geometry/parallel.py, odl/tomo/operators/xray_trafo.py, odl/tomo/util/trafos.py, odl/util/phantom.py, test/tomo/backends/astra_setup_test.py, test/tomo/geometry/geometry_test.py
Initial fixes for the conebeam fixes, needs some more I suppose. Now uses the generalized functions wherever possible.
=> Conebeam cone fixes

examples/visualization/show_update_1d.py, examples/visualization/show_update_2d.py, odl/solvers/__init__.py, odl/solvers/findroot/newton.py, odl/solvers/iterative/iterative.py, odl/solvers/scalar/gradient.py, odl/solvers/util/partial.py, odl/solvers/vector/newton.py, odl/util/graphics.py
Solves issue #213 and some other style issues with partials:
* Changed `partial.send(x)` to `partial(x)`
* Add `PrintTimePartial` (cudos do @moosmann for code)
=> ENH: change send -> __call__ for partials

odl/set/domain.py
Another short pull, would close issue #140.
=> ENH: add IntervalProd.__getitem__

examples/visualization/show_2d_complex.py, odl/discr/discr_ops.py, odl/trafos/wavelet.py, test/discr/discr_ops_test.py, test/trafos/wavelet_test.py
Renaming done as follows:
* DiscretePartDeriv -> PartialDerivative
* DiscreteGradient -> Gradient
* DiscreteDivergence -> Divergence
* DiscreteWaveletTransform ->WaveletTransform
* DiscreteWaveletTransformInverse -> WaveletTransformInverse
=> Issue 238  discrete prefix

odl/discr/discr_ops.py, odl/discr/grid.py
Closes #242 by adding laplacian operator. Not optimized currently, but way better than calling `Gradient.adjoint * Gradient`.
=> Issue 242 laplacian

odl/discr/discretization.py, odl/discr/lp_discr.py, odl/operator/operator.py, odl/space/base_ntuples.py, odl/space/ntuples.py
This is an initial commit, work in progress on #273, example of using it [available in odl-examples](https://github.com/odlgroup/odl-examples/blob/master/linear_deformation.py).
=> Issue 273 add linear deformations

examples/visualization/show_ntuple.py, examples/visualization/show_update_2d.py, odl/solvers/util/partial.py, odl/util/graphics.py
Some fixes, now works with (at least)
Please verify for other platforms and we can finally merge. The following should be tested:
* All tests in examples/visualization.
* Some test using ShowPartial, for example `odl-examples/pde_laplacian.py`.
Ping @kohr-h, @moosmann
=> Issue 277  show

doc/source/math/discretization.rst, doc/source/math/solvers/advanced/chambolle_pock.rst, doc/source/math/solvers/advanced/proximal_operators.rst, doc/source/math/solvers/solvers.rst, examples/solvers/chambolle_pock_deconvolve.py, examples/solvers/chambolle_pock_denoising.py, odl/discr/discr_ops.py, odl/set/space.py, odl/solvers/__init__.py, odl/solvers/advanced/__init__.py, odl/solvers/advanced/chambolle_pock.py, odl/solvers/advanced/proximal_operators.py, odl/solvers/iterative/iterative.py, odl/solvers/scalar/steplen.py, odl/solvers/util/partial.py, odl/solvers/vector/newton.py, test/discr/discr_ops_test.py, test/solvers/advanced/chambolle_pock_test.py, test/solvers/advanced/proximal_operator_test.py
Created a pull request of this to be able to comment. @moosmann and @aringh are main authors.
=> Issue 226  chambolle pock solver

odl/discr/lp_discr.py, odl/set/pspace.py, odl/space/base_ntuples.py, odl/util/graphics.py
Changed title to come first since this is the only real standard we can apply to all cases, and it makes sense somewhat.
=> ENH: change order of show to have title first in all cases, close #252

examples/visualization/show_2d.py, odl/discr/lp_discr.py
=> ENH: add option to show by coordinate in DiscreteLp

odl/discr/lp_discr.py
=> ENH: add uniform_discr_fromintv

examples/solvers/scipy_solvers.py, odl/operator/oputils.py
Very simple code that adds interface to scipys linear solvers, also has a simple example.
=> ENH: add as_scipy_operator, closes #323

doc/source/guide/glossary.rst, doc/source/math/discretization.rst, odl/discr/discr_mappings.py, odl/discr/discr_ops.py, odl/discr/discretization.py, odl/discr/lp_discr.py, test/discr/lp_discr_test.py
=> API: rename restriction and extension

odl/solvers/scalar/steplen.py
Intended as an alternative to #345
* Treats `NaN` as errors and properly throws an exception on them
* Validates initial function value
* Small optimization in case function is infinite.
=> Add data checks for BacktrackingLineSearch

odl/space/fspace.py
=> BUG: fix error due to direct usage of tuple in 1d meshgrids

odl/discr/discr_mappings.py, test/discr/discr_mappings_test.py
=> BUG: fix interpolation not writing to CUDA arrays

examples/tomo/filtered_backprojection_parallel_2d.py, odl/operator/operator.py
A simple example of implementing FBP in ODL, shows both syntax and is probably requested by several users.
=> ENH: add a fbp example

README.md, odl/__init__.py, odl/util/testutils.py
The old readme made no sense, this new one works perfectly.
=> ENH: add odl.test() call, update readme

odl/tomo/geometry/__init__.py, odl/tomo/geometry/parallel.py, odl/tomo/geometry/spect.py, test/tomo/geometry/spect_geometry_test.py
Added a class for SPECT parallel hole geometry and tests for it.
=> Issue 303  spect geometry

odl/util/graphics.py
Add handling of some corner cases where we got nonsense values, now tries to "make the best of it". Also unified complex and real handling in these cases.
=> ENH: improve show axes in case of nan or inf

odl/tomo/backends/stir_bindings.py
@niinimaki 
This fix is for you, does it look OK? Can you try it out?
=> BUG: fix bug with stirextra import in stir_bindings

doc/source/math/trafos/fourier_transform.rst, odl/trafos/fourier.py, test/trafos/fourier_test.py
* Allow adjoint on real transform
* Add test for the above
* Improve test structure in some fourier tests
* Change fftw specific functions to throw if impl is not fftw
=> ENH: FFT improvements. Closes #389

odl/discr/diff_ops.py, odl/discr/discr_ops.py, test/discr/diff_ops_test.py
This adds boundary handling behavior to the `Gradient` family of operators.
* Added `periodic` boundary condition
* Added tests for many more boundary conditions using fixtures
* General cleanup of diff_ops tests
* Added all boundary conditions to `Gradient`, `Divergence` and `Laplacian`
* Added correct handling of `'constant'` boundary condition which causes the operator to become nonlinear.
=> Issue 402  gradient boundary

odl/operator/operator.py
Been wanting to do this for a while, minor optimization in case of several multiplications.
=> ENH: optimzize repeated scalar times operator

odl/discr/discr_mappings.py, odl/operator/default_ops.py, odl/operator/operator.py, odl/operator/pspace_ops.py, odl/space/fspace.py, odl/space/ntuples.py, odl/tomo/backends/stir_bindings.py, odl/trafos/fourier.py, odl/trafos/wavelet.py, test/operator/pspace_ops_test.py, test/trafos/fourier_test.py
Closes #416 
Basically a style update.
=> API: change `dom`/`ran` to `domain`/`range`.

odl/discr/discretization.py, odl/discr/grid.py, odl/discr/partition.py, odl/space/base_ntuples.py, odl/space/pspace.py
See #424, but this adds it to several more places and follows numpy convention.
=> ENH: add len to several places

odl/discr/lp_discr.py, odl/space/fspace.py, test/discr/lp_discr_test.py, test/solvers/advanced/chambolle_pock_test.py
Convenience fix, result should be obvious from tests. Also had to fix an erroneous test in chambolle pock (that was "saved" before this change).
=> ENH: allow broadcasting in discr element

odl/discr/discretization.py, odl/discr/lp_discr.py, odl/set/space.py, odl/space/cu_ntuples.py, odl/space/fspace.py, odl/space/ntuples.py, odl/space/pspace.py, test/largescale/space/fn_base_slow_test.py
Enforces that the call
x = x.space.element(x)
does nothing. Implements this in the spaces and adds a test.
=> API: enforce element(vec) noop

odl/tomo/backends/astra_setup.py, odl/tomo/backends/scikit_radon.py, odl/util/graphics.py, test/tomo/operators/ray_trafo_test.py
Closes #435 
Can you check if you get the correct result?
=> BUG: fix rotation by 90 degrees for 2d parallel

odl/discr/grid.py, odl/discr/lp_discr.py, odl/discr/partition.py, odl/util/graphics.py
* Fix corner values using actual corners of the set instead of the minimum/maximum gridpoint
* Exposed `squeeze` and `coord_vectors` in `RectPartition`
This has so far not fixed the mouseover not showing coordinates issue, which should also be fixed.
=> BUG: fix values of show axes

odl/operator/default_ops.py
Minor pull, noticed that these guys were missing.
=> Add NormOperator and DistOperator

odl/discr/diff_ops.py, odl/discr/discr_ops.py, odl/discr/grid.py, odl/operator/default_ops.py, odl/operator/pspace_ops.py, odl/set/space.py, odl/solvers/advanced/proximal_operators.py, odl/solvers/util/callback.py
=> MAINT: improve __init__ docstrings

doc/source/refs.rst, odl/solvers/advanced/chambolle_pock.py, odl/solvers/advanced/douglas_rachford.py
Mostly a documentation update but also some slight functionality.
=> ENH: add nonlinear chambolle-pock, improve doc

odl/space/base_ntuples.py, test/solvers/advanced/douglas_rachford_test.py, test/space/ntuples_test.py
Minor functionality addition, enables `float(x), complex(x), int(x) and long(x)` on 1 element `NtuplesBase` vectors.
=> ENH: add float, complex, int and long to base_ntuples

odl/discr/discr_mappings.py, odl/operator/default_ops.py, odl/operator/operator.py, odl/solvers/advanced/chambolle_pock.py, odl/solvers/advanced/douglas_rachford.py, odl/solvers/advanced/forward_backward.py, odl/solvers/iterative/iterative.py, odl/solvers/scalar/gradient.py, odl/space/fspace.py, odl/trafos/fourier.py, test/discr/lp_discr_test.py, test/operator/operator_test.py, test/space/fspace_test.py, test/space/ntuples_test.py, test/space/pspace_test.py, test/tomo/operators/ray_trafo_test.py, test/trafos/fourier_test.py, test/util/vectorization_test.py
=> TST: add inplace test for tomo projectors, closes #266

release.sh, tools/release.sh
Preliminary PR for a release script for simplification. Never tested it :-)
=> REL: add release script

doc/source/guide/glossary.rst, doc/source/release_notes.rst, odl/__init__.py, setup.py
Bump the version since the addition of a new top level package (`deform`) should definitely be a new minor version
=> REL: create 0.4.0 release notes

odl/discr/tensor_ops.py, odl/operator/default_ops.py, odl/set/space.py, odl/solvers/advanced/proximal_operators.py, test/space/ntuples_test.py
=> API: change definition of LinearSpaceVector.multiply and divide

odl/diagnostics/operator.py, odl/diagnostics/space.py, odl/discr/discretization.py, odl/operator/default_ops.py, odl/set/space.py, odl/util/testutils.py, test/discr/lp_discr_test.py
=> BUG: fix missing opnorm calc in diagnostics

doc/source/release_notes.rst, examples/solvers/chambolle_pock_deconvolve.py, examples/solvers/chambolle_pock_denoising.py, examples/solvers/chambolle_pock_tomography.py, examples/solvers/denoising_with_entropy_type_regularization.py, odl/operator/oputils.py, test/operator/oputils_test.py
=> ENH: improve implementation of power_method_opnorm to terminate early

doc/source/release_notes.rst, odl/tomo/backends/astra_cpu.py, odl/tomo/backends/astra_cuda.py, odl/tomo/backends/astra_setup.py, odl/tomo/operators/ray_trafo.py, odl/util/utility.py, test/largescale/tomo/ray_transform_slow_test.py, test/tomo/operators/ray_trafo_test.py
Closes #455 (float64 in astra) and possibly #254 (`writable_array` context manager) if the implementation is deemed OK. Also adds tests for this (but only for slow tests, due to performance).
=> Add astra float64 support and writable_array context manager

doc/source/release_notes.rst, odl/operator/operator.py
Also some fixes to the release notes
=> API: Remove simple_operator, closes #539

odl/discr/diff_ops.py, odl/discr/discr_mappings.py, odl/discr/discr_ops.py, odl/operator/default_ops.py, odl/operator/operator.py, odl/operator/pspace_ops.py, odl/set/domain.py, odl/trafos/wavelet.py
Quite trivial pull, moved doc from _call to __init__. Should have no changes to actual code.
=> DOC: move documentation from _call to __init__, closes #530

doc/source/release_notes.rst, odl/discr/partition.py, test/largescale/tomo/ray_transform_slow_test.py, test/tomo/operators/ray_trafo_test.py
Gives a better syntax for nonuniform partitions, old syntax still works.
=> Issue 356  nonuniform partition

odl/discr/diff_ops.py, odl/operator/oputils.py, test/discr/diff_ops_test.py
* Add new boundary condition: ``order0``
* Change old ``edge_order`` parameters to ``pad_mode`` style parameters
* Significantly simplified the implementation of ``finite_diff``
* Some other minor fixes snuck in.
=> ENH: Improvements to finite_diff and others

examples/solvers/chambolle_pock_deconvolve.py, examples/solvers/chambolle_pock_tomography.py, examples/solvers/douglas_rachford_primal_dual_heron.py, odl/solvers/advanced/proximal_operators.py, odl/solvers/functional/default_functionals.py, odl/solvers/functional/functional.py, test/largescale/solvers/advanced/proximal_operator_slow_test.py, test/solvers/advanced/chambolle_pock_test.py, test/solvers/advanced/douglas_rachford_test.py, test/solvers/advanced/forward_backward_test.py, test/solvers/advanced/proximal_operator_test.py, test/solvers/advanced/proximal_utils_test.py
Update the name `proximal_zero` to `proximal_const_func`.
=> API/MAINT: change name of proximal_zero to proximal_const_func.

odl/solvers/functional/functional.py, test/solvers/functional/functional_test.py
Cherry picked from #587, should be simple to review.
Things that need to be done:
* Add a test
Things that could be done:
* Add some intelligence so that this can only be created if it is useful (i.e. if the functional has a proximal). This could be nice in some cases I guess, but in others it could also give hard to follow logic.
* Perhaps add some logic to evaluate the functional in some sense (perhaps solve the optimization problem, somehow). Not sure at all if this is a good idea.
=> ENH: Add default convex conjugate, closes #570

odl/solvers/functional/default_functionals.py
Cherry picked from #587, should be simple to review.
Further changes to be done:
* Add `IndicatorNonnegativity`
* Add test
=> ENH: Add IndicatorBox functional

test/solvers/functional/default_functionals_test.py, test/solvers/functional/functional_test.py
Basically removed `PLACES` everywhere and let `almost_equal` figure it out.
=> BUG: fix functional failures with cuda, closes #538

examples/visualization/show_2d.py, odl/discr/lp_discr.py
Slight functionality extension to show, can now properly display subsets of an image.
=> ENH: Allow show with coord as subset of axis

odl/operator/default_ops.py, odl/operator/operator.py, odl/solvers/functional/default_functionals.py, odl/solvers/functional/functional.py, test/solvers/functional/functional_test.py
Adds the product of two functionals, see #581.
=> Issue 581  functional product

test/discr/diff_ops_test.py
Minor fix, but should settle these pesky bugs. Basically require slightly lower resolution in general.
=> BUG: Fix failures in diff_ops_test with cuda, closes #585

odl/solvers/advanced/proximal_operators.py, odl/solvers/functional/default_functionals.py, odl/solvers/functional/functional.py, test/solvers/advanced/proximal_utils_test.py
This is not completely done yet, but I'm creating the pull request so that @kohr-h and @adler-j can start checking if it looks ok.
As the name says, this pull request is mainly #562, but as I was anyway working with the proximals I also incorporated in this branch #572.
=> Issue 562  typset math in proximals

odl/util/vectorization.py, test/util/vectorization_test.py
Fixed #603 and added a test for it
=> BUG: fix bug causing classes to not be vectorizable, closes #603

odl/solvers/functional/__init__.py, odl/solvers/functional/example_funcs.py, test/solvers/iterative/iterative_test.py, test/solvers/vector/newton_test.py
Minor yet probably useful addition. We could add more examples if we want.
=> ENH: Add rosenbrock functional, see #600

odl/solvers/functional/__init__.py, odl/solvers/functional/derivatives.py
TODO:
* ~~Add hessian~~
Ready for review, I'd say I'm actually quite happy about how this turned out.
=> ENH: Add NumericalGradient, see #623

odl/discr/lp_discr.py, odl/discr/partition.py
- Fixes issue #675, error when the upper bound is given to `show(coords=[...])`
- Add `RectPartition.index`
- Add `RectPartition.bydimension`
=> Issue 675  show upper bound

.travis.yml, odl/pytest.ini, odl/util/pytest_plugins.py, odl/util/testutils.py, pytest.ini
Fix for #679, works in my working environment, but I'll test it with more configurations. Windows tests are also appreciated :-)
=> Issue 679  collect ignore

odl/discr/tensor_ops.py, odl/solvers/functional/default_functionals.py, odl/test/largescale/solvers/nonsmooth/proximal_operator_slow_test.py, odl/util/pytest_plugins.py
Initial commit for `GroupL1Norm` needs #555 to proceed.
TODO:
=> ENH: Add GroupL1Norm, closes #619

doc/source/guide/derivatives_guide.rst, doc/source/guide/guide.rst, doc/source/math/derivatives_guide.rst, doc/source/math/math.rst
Adds documentation on what we mean by derivatives, gradients etc.
=> Issue 632  document derivatives

examples/tomo/filtered_backprojection_cone_2d.py, examples/tomo/filtered_backprojection_cone_3d.py, odl/test/largescale/tomo/analytic_slow_test.py, odl/tomo/analytic/__init__.py, odl/tomo/analytic/filtered_back_projection.py, odl/tomo/geometry/parallel.py
Tests not yet done using ASTRA (Since I lack it at this machine) but the overall structure should stand.
=> ENH: Add fbp_op utility with tests

examples/deform/linearized_fixed_displacement.py, examples/deform/linearized_fixed_template.py, examples/trafos/wavelet_trafo.py, odl/deform/linearized.py, odl/discr/lp_discr.py, odl/test/deform/linearized_deform_test.py
Solves issue #693 and two other bugs found when running `pytest --examples`
=> Issue 693  vector field space rename

odl/deform/mass_preserving.py
Operators and functions for general and mass-preserving deformation are developed.
=> Issue 464  deformation operators

odl/tomo/data/uncompr_bin.py
Fixes an I/O bug that a user encountered. Basically `np.fromfile` refused to read from a file which was open by all measures. The error was similar to the one in [this issue](https://github.com/numpy/numpy/issues/6246) but the mentioned potential solution of unbuffered reading did not do the trick. I went for low-level reading into the array buffer instead, which solves the issue.
=> BUG: fix I/O issue with failing np.fromfile

doc/source/refs.rst, examples/solvers/nuclear_norm_minimization.py, examples/solvers/nuclear_norm_tomography.py, odl/phantom/noise.py, odl/solvers/functional/default_functionals.py, odl/solvers/nonsmooth/proximal_operators.py, odl/solvers/util/callback.py, odl/space/pspace.py, odl/test/largescale/solvers/nonsmooth/proximal_operator_slow_test.py, odl/test/solvers/functional/default_functionals_test.py, odl/test/space/pspace_test.py
Adds `NuclearNorm` class with two examples.
=> Issue 690  nuclear norm

examples/solvers/denoising_with_entropy_type_regularization.py, odl/solvers/nonsmooth/chambolle_pock.py
=> Examples cleanup

odl/operator/default_ops.py, odl/operator/oputils.py
I thought this one would be easy but it turned out to be a mess from a mathematics standpoint. Ready fore review anyway.
closes #698.
=> Issue 698  real part complex part

odl/solvers/functional/default_functionals.py
Improved the math documentation of the KL functionals to be more readable to the "layman".
=> DOC: Improve doc of KL functionals, see #743

doc/source/dev/dev.rst, doc/source/dev/document.rst, doc/source/dev/testing.rst
Adds documentation on how tests work in ODL along with implementing new ones.
=> DOC: Initial work in testing documentation, see #667

odl/discr/tensor_ops.py, odl/solvers/nonsmooth/forward_backward.py, odl/test/discr/tensor_ops_test.py
Added PointwiseSum utility by using the PointwiseInner functionality.
In the future, we can optimize this.
=> Add pointwise sum

odl/solvers/util/steplen.py, odl/test/solvers/util/steplen_test.py
Add option to have a line search where the step length depends on the iteration count.
=> ENH: Add PredefinedLineSearch

odl/tomo/analytic/filtered_back_projection.py
Simple pull splitting the `fbp_op` into two such that the filter can be accessed separately.
Closes #779
=> MAINT: expose FBP filter operator

odl/phantom/geometric.py, odl/phantom/transmission.py
=> BUG: avoid zero division in ellipse phantom for shape=1 axes

examples/solvers/lbfgs_tomography_tv.py, odl/solvers/functional/default_functionals.py, odl/test/solvers/functional/default_functionals_test.py
Initial work on Moreau envelope, it seems we need to add more properties. TODO:
=> ENH: Add Moreau envelope

odl/solvers/util/callback.py
Callback for showing and saving the intermediate iterates. Closes #639
=> Issue 639  callback show and save

odl/operator/operator.py
Small (actually quite noticeable for OperatorComp) improvement to the derivative computation given linear operators.
=> MAINT: Improve performance of operator algebra derivative if linear

doc/source/guide/numpy_guide.rst, examples/ufunc_ops/ufunc_basics.py, examples/ufunc_ops/ufunc_composition.py, examples/ufunc_ops/ufunc_solvers.py, odl/discr/lp_discr.py, odl/discr/tensor_ops.py, odl/phantom/misc_phantoms.py, odl/solvers/functional/default_functionals.py, odl/solvers/iterative/statistical.py, odl/solvers/nonsmooth/proximal_operators.py, odl/space/base_ntuples.py, odl/space/npy_ntuples.py, odl/space/pspace.py, odl/test/discr/lp_discr_test.py, odl/test/solvers/functional/default_functionals_test.py, odl/test/solvers/functional/functional_test.py, odl/test/space/ntuples_test.py, odl/test/space/pspace_test.py, odl/test/tomo/operators/ray_trafo_test.py, odl/ufunc_ops/ufunc_ops.py, odl/util/ufuncs.py
I'm doing this on the tensors branch anyway, but thought I separate it out to remove clutter from that PR.
Similar PR coming up for odlcuda.
=> MAINT: cosmetic rename of ufunc object

odl/discr/discr_mappings.py, odl/discr/discr_ops.py, odl/discr/discretization.py, odl/discr/grid.py, odl/discr/lp_discr.py, odl/discr/partition.py, odl/operator/oputils.py, odl/phantom/noise.py, odl/set/domain.py, odl/set/sets.py, odl/space/base_ntuples.py, odl/space/fspace.py, odl/space/npy_ntuples.py, odl/space/pspace.py, odl/space/space_utils.py, odl/space/weighting.py, odl/test/discr/discr_ops_test.py, odl/test/util/normalize_test.py, odl/test/util/vectorization_test.py, odl/tomo/backends/astra_cuda.py, odl/util/__init__.py, odl/util/normalize.py, odl/util/utility.py
Utility for more extensible and robust printing of signatures, plus application to some cases in `discr` and `partition`. Quite some improvements in the printed strings IMO.
=> Signature helper

odl/space/npy_ntuples.py, odl/space/pspace.py, odl/space/weighting.py, odl/test/space/ntuples_test.py
Had overlooked this TODO in #810, fixing now.
=> MAINT: rename CustomInnerProduct -> CustomInner

odl/solvers/functional/default_functionals.py
I felt this example grealy clarifies what the envelope does.
=> DOC: Add example to MoreauEnvelope documentation

odl/discr/lp_discr.py, odl/operator/tensor_ops.py, odl/space/npy_ntuples.py, odl/space/pspace.py, odl/space/weighting.py, odl/util/utility.py
Okay, last one, then sleep.
Some fixes to doc and other things in weighting, nothing spectacular.
=> MAINT: rename custom inner classes

odl/test/deform/linearized_deform_test.py, odl/test/discr/diff_ops_test.py, odl/test/discr/lp_discr_test.py, odl/test/operator/tensor_ops_test.py, odl/test/solvers/functional/default_functionals_test.py, odl/test/space/fspace_test.py, odl/test/space/ntuples_test.py, odl/test/space/pspace_test.py, odl/test/trafos/backends/pyfftw_bindings_test.py, odl/test/trafos/backends/pywt_bindings_test.py, odl/test/trafos/fourier_test.py, odl/test/trafos/util/ft_utils_test.py, odl/test/trafos/wavelet_test.py, odl/test/util/normalize_test.py, odl/test/util/numerics_test.py
Booring, but could actually use a proper readhthrough since it was lots of manual copy-paste, misstakes could have happened.
=> MAINT: Convert tests to use simple_fixture where appropriate

examples/solvers/chambolle_pock_tomography.py, examples/solvers/conjugate_gradient_tomography.py, examples/solvers/douglas_rachford_pd_tomography_tv.py, examples/solvers/lbfgs_tomography.py, examples/solvers/lbfgs_tomography_tv.py, examples/solvers/nuclear_norm_tomography.py, examples/solvers/proximal_gradient_wavelet_tomography.py, examples/solvers/proximal_lang_tomography.py, examples/tomo/filtered_backprojection_cone_2d.py, examples/tomo/filtered_backprojection_cone_3d.py, examples/tomo/filtered_backprojection_helical_3d.py, examples/tomo/filtered_backprojection_parallel_2d.py, examples/tomo/filtered_backprojection_parallel_3d.py, examples/tomo/ray_trafo_circular_cone.py, examples/tomo/ray_trafo_fanflat.py, examples/tomo/ray_trafo_helical.py, examples/tomo/ray_trafo_parallel_2d.py, examples/tomo/ray_trafo_parallel_3d.py, odl/tomo/operators/ray_trafo.py
I'm keeping with the theme of the day of removing code, i.m.o. this is much cleaner. An issue is that users are not given sufficient information that they *REALLY* want to install ASTRA.
=> Issue 822  ray trafo impl default

README.md, conda/meta.yaml, doc/source/release_notes.rst, odl/__init__.py, setup.py
PR for the release. Should go in quickly.
=> Release 0.5.3

doc/source/getting_started/installing.rst
Fixes to minor comments that were encountered when a new user installed ODL. Should slightly improve readability of the guide.
=> DOC: Minor improvements to installing.rst

odl/discr/discr_mappings.py, odl/discr/discretization.py, odl/discr/grid.py, odl/discr/partition.py, odl/set/domain.py, odl/set/sets.py, odl/solvers/iterative/iterative.py, odl/space/base_ntuples.py, odl/space/fspace.py, odl/space/npy_ntuples.py, odl/space/pspace.py, odl/space/weighting.py, odl/test/discr/grid_test.py, odl/test/discr/lp_discr_test.py, odl/test/discr/partition_test.py, odl/test/set/domain_test.py, odl/test/solvers/iterative/iterative_test.py, odl/test/space/fspace_test.py, odl/test/space/ntuples_test.py, odl/test/space/pspace_test.py
Closes an old friend.
Also adresses #843, adding `__hash__` to spaces.
Todo:
=> Kaczmarzs method and __hash__

odl/solvers/util/callback.py
The user can specify how often the iteration number should be printed.
Edit: this fixes #870
=> ENH: change in CallbackPrintIteration.

examples/solvers/chambolle_pock_tomography_tgv.py, odl/operator/default_ops.py
This adds a simple example of solving TGV(2) minimized tomography.
=> ENH: Add TGV example

odl/set/space.py
Quite sexy syntax, if I may say it myself. Should we update the examples to use this?
=> Issue 859  linearspace products

odl/solvers/functional/default_functionals.py, odl/test/largescale/solvers/nonsmooth/default_functionals_slow_test.py, odl/test/solvers/functional/default_functionals_test.py
Fix for issue #837. I have also added a test.
=> Issue 837  bug derivative quadratic functional

examples/tomo/backends/astra_performance_cuda_parallel_2d_cg.py
=> MAINT: Fix funny spelling error in astra performance example

odl/operator/operator.py, odl/operator/pspace_ops.py, odl/set/space.py, odl/test/space/ntuples_test.py
Thus turned out to be harder than I anticipiated, since stuff like (rn vector) + (operator) started giving wierd stuff. Thankfully I (think) I've solved it, but this is non-trivial and could use a thorough review.
Closes three issues anyhow!
=> Issue 319  linearspace more permissive

odl/tomo/data/mrc.py
Fixes so the doc to properly match what we do and require according to the specification.
Also fixed some naming etc to follow this, and simplified the implementation to fix DRY violations.
=> MAINT: Clear up doc of MRC extended header, simplify implementation, see #913

odl/solvers/util/callback.py, odl/util/graphics.py
Minor fix, causes the title of the `CallbackShow` window to update automatically, also supports user given titles.
=> ENH: Display iteration number in CallbackShow

odl/set/sets.py, odl/set/space.py, odl/test/set/space_test.py, odl/util/testutils.py
Fixes the first half of issue #931, does not add functionality for comparison.
=> Issue 931  linearspace cmp

examples/tomo/backends/astra_performance_cuda_cone_3d_cg.py, odl/tomo/backends/astra_cuda.py
Minor example. Clearly needs another example where we use pygpu on the ODL side.
=> ENH: Add 3d cone cude performance example with ASTRA

odl/tomo/backends/scikit_radon.py
It now supports to compute the Radon transform for only one angle
=> Remove bug in scikit radon.

odl/operator/__init__.py, odl/operator/fn_ops.py
This is the current version of the code that we discussed in #936. Please have a look and give feedback. Thanks!
=> initial version of sampling and embedding operators

odl/operator/operator.py
Minor yet sometimes important optimization
=> ENH: Minor optimization of OperatorComp.derivative

odl/solvers/util/callback.py
I found this syntax very nice myself, is it something we want?
=> ENH: Add composition of callback with operator

odl/operator/oputils.py
Could use an expedited review since this causes all other PR's to fail.
=> BUG: Fix SciPy 0.19 bug with as_scipy_operator

odl/solvers/functional/functional.py
Simple implementation for when it exists and we can "easily" find it.
=> ENH: Add FunctionalComp.gradient.derivative

.travis.yml
WIP PR to check if this works and how fast it runs. Allegedly faster because docker is used in case of `sudo:false`, but I have to unconditionally install the LaTeX packages.. we'll see.
=> BLD: change to no-sudo Travis build, closes #927

odl/solvers/util/callback.py
"Emergency bugfix" for `CallbackShow` which raised an exception for some of the examples. The `*args` mess up everything.
This needs to go in before the version bump.
=> BUG: fix multiple title args in CallbackShow

doc/source/dev/release.rst
Some improvements from experience gained during the last release.
=> DOC: improvements to release doc

odl/solvers/smooth/nonlinear_cg.py
Fix for the failing Sphinx documentation build.
=> DOC: remove duplicate Notes section in nonlinear CG docs

odl/discr/discr_ops.py, odl/discr/grid.py, odl/discr/partition.py, odl/set/domain.py, odl/test/discr/discr_ops_test.py, odl/test/tomo/backends/astra_setup_test.py, odl/trafos/fourier.py, odl/trafos/util/ft_utils.py
~~Based on #995, needs rebase after that one is merged.~~
Based on master now, ready for review.
=> Issue 671  mixed uni nonuni

odl/discr/discr_ops.py, odl/discr/grid.py
Somehow this fix didn't make it into #996
=> MAINT: style fixes to discr_ops and grids

odl/space/pspace.py
=> BUG: Fix warning about complex numbers in pspace, closes #799

examples/operator/simple_operator.py
Very minor improvement proposal
=> STYLE: Minor improvement to simple_operator example

odl/operator/operator.py, odl/set/space.py, odl/solvers/util/callback.py, odl/test/operator/operator_test.py, odl/util/graphics.py
Finally getting this done, now less bug prone.
=> ENH: Add additional protection against returning wrong value in operator, closes #962

odl/phantom/misc_phantoms.py
Rather simple addition of a phantom that is simply some text. Useful as an example for many cases.
Inspired by our discussion in #15.
Examples:
```python
space = odl.uniform_discr([-1, -1], [1, 1], [300, 300])
for font in ['arial', 'impact', 'calibri']: 
odl.phantom.text(space, text='ODL', font=font).show(font)
```
=> ENH: Add text phantom

odl/solvers/util/callback.py
* Add step in some places where it was obviously missing
* Update repr in some places
* Made `func` style arguments give a DeprecationWarning, instead recommend use of composition.
=> Callback improvements

odl/solvers/nonsmooth/chambolle_pock.py
Improves some minor stuff in the `chambolle_pock_solver`. In a simple benchmark (the TGV example) this improved run-time from 19.5 seconds down to 14.6, a ~25% improvement.
=> MAINT: Performance improvements to chambolle pock

odl/contrib/tomo/README.md, odl/contrib/tomo/__init__.py, odl/contrib/tomo/elekta.py, odl/contrib/tomo/examples/elekta_icon_tomography.py, odl/solvers/nonsmooth/douglas_rachford.py, odl/test/tomo/backends/astra_cuda_test.py, odl/tomo/analytic/filtered_back_projection.py, odl/tomo/backends/astra_cuda.py, odl/tomo/operators/ray_trafo.py
Planned to only add a contrib.tomo.elekta package but got some performance issues while doing it that I fixed.
With that said, this does not currently work on my machine, specifically the returned volume is all zeros. I've checked and it seems like we're feeding ASTRA non-zero stuff but ASTRA returns all zeros (I checked before and after the astra call) so that needs debugging.
Could use a review of the performance stuff specifically.
=> Issue 206  premade geometries

odl/set/sets.py, odl/util/utility.py
=> Issue 863  finite set

odl/discr/discretization.py, odl/discr/grid.py, odl/discr/lp_discr.py, odl/phantom/geometric.py, odl/set/sets.py, odl/set/space.py, odl/solvers/util/steplen.py, odl/space/base_ntuples.py, odl/space/npy_ntuples.py, odl/test/space/ntuples_test.py, odl/tomo/geometry/detector.py, odl/tomo/geometry/geometry.py, odl/util/pytest_plugins.py
Even more boring performance hunting. Now made a particular (internal) script run about 30-40% faster by doing this. Additionally, improves the runtime of the test suite by 5% when compared to master.
Also fixed a bug in running pytest.
=> Optimizations to the case of small data

README.md
I feel that we should add this badge, if nothing else because it conveys that this is a serious library with good coverage. Do we agree?
=> DOC: Add coverage badge

odl/test/tomo/operators/ray_trafo_test.py
Fixed scaling by magnification factor, test is now quite accurate for all geometries.
=> TST: Improve angles test for divergent beam geometries, closes #1053

odl/util/graphics.py
Minor fix to an irritating issue.
=> BUG: Fix bug with colorbar ticks missing in some cases

odl/contrib/fom/__init__.py, odl/contrib/fom/examples/supervised_comparison.py, odl/contrib/fom/supervised.py
This is related to issue #1017
=> Issue 1017  fom

odl/operator/default_ops.py, odl/operator/operator.py
Making a small initial PR to review the concept. If we go further we can start adding this to various classes.
=> ENH: Add Operator.norm, closes #1065

odl/solvers/functional/functional.py
This is a tiny pull request. It only implements the infimal convolution as an abstract functional. The only easy implementation is the convex conjugate.
=> add infimal convolution as an abstract functional

odl/phantom/geometric.py
=> ENH: Add smooth cuboid phantom

odl/__init__.py, odl/contrib/datasets/README.md, odl/contrib/datasets/__init__.py, odl/contrib/datasets/ct/__init__.py, odl/contrib/datasets/ct/examples/fips_reconstruct.py, odl/contrib/datasets/ct/fips.py, odl/contrib/datasets/mri/__init__.py, odl/contrib/datasets/mri/examples/tugraz_reconstruct.py, odl/contrib/datasets/mri/tugraz.py, odl/contrib/datasets/util.py, odl/operator/default_ops.py, odl/phantom/geometric.py
Adds the data from http://imsc.uni-graz.at/mobis/internal/platform_aktuell.html and stuff needed for reconstruction of it, in particular a complex modulus operator.
Example reconstructions:
=> Add TU Graz mri data

odl/contrib/theano/README.md, odl/contrib/theano/__init__.py, odl/contrib/theano/examples/theano_layer_matrix.py, odl/contrib/theano/layer.py, odl/contrib/theano/test/theano_test.py
Very small commit that adds basic theano functionality.
=> ENH: Add theano support, closes #1098

odl/contrib/pytorch/README.md, odl/contrib/pytorch/__init__.py, odl/contrib/pytorch/examples/basic.py, odl/contrib/pytorch/layer.py, odl/contrib/pytorch/test/layer.py
~~Almost done, there's just an issue with stride 0 arrays breaking some stuff, the example is not quite complete, and tests are missing.~~ See TODO list
But this is the deep learning framework with the slimmest wrapper so far. Almost trivial.
TODOs:
=> ENH: pytorch integration

examples/solvers/kaczmarz_tomography.py, odl/discr/grid.py, odl/discr/partition.py, odl/solvers/iterative/iterative.py, odl/tomo/geometry/conebeam.py, odl/tomo/geometry/parallel.py
Before I spend too long on this, I could use some feedback on the interface. Does it look OK?
@kohr-h and @MatthiasJE
=> WIP: Add indexing to geometries

README.md
Add link to DOI for TVR-DART (DGCI 2017) article. Also add link to github for code associated to "Generalized Sinkhorn iterations for regularizing inverse problems using optimal mass transport"
=> DOC: update readme with new links to article and code.

odl/contrib/tomo/elekta.py
Very minor fixes to the elekta stuff
=> MAINT: Improve handling of angles in elekta

odl/contrib/fom/examples/noise_power_spectrum.py, odl/contrib/fom/supervised.py
This adds NPS computations, I guess we should also add MTF.
=> ENH: Add noise power spectrum to foms

examples/solvers/kaczmarz_tomography.py
=> ENH: Change kaczmarz to parallel beam

CONTRIBUTORS.md, README.md
I've created `CONTRIBUTORS.md` and updated the text of the section in the readme.
Please review and comment on if you feel your work has been miss-represented in any way!
=> DOC: Update contributors and add CONTRIBUTORS.md, closes #1123

odl/contrib/fom/test/test_supervised.py, odl/discr/discr_mappings.py, odl/discr/lp_discr.py, odl/test/discr/discr_ops_test.py, odl/test/discr/lp_discr_test.py, odl/test/largescale/solvers/nonsmooth/default_functionals_slow_test.py, odl/test/largescale/tomo/analytic_slow_test.py, odl/test/largescale/tomo/ray_transform_slow_test.py, odl/test/largescale/trafos/fourier_slow_test.py, odl/test/solvers/functional/default_functionals_test.py, odl/test/solvers/functional/functional_test.py, odl/test/solvers/nonsmooth/proximal_utils_test.py, odl/test/tomo/backends/astra_cuda_test.py, odl/test/tomo/geometry/geometry_test.py, odl/test/tomo/operators/ray_trafo_test.py, odl/test/util/numerics_test.py, odl/trafos/util/ft_utils.py, odl/util/pytest_plugins.py, odl/util/testutils.py, odl/util/utility.py
=> ENH: simplify usage of simple_fixture with skipif-wrapped args

README.md
=> DOC: Add The MAX IV imaging concept to the readme

.travis.yml
Testing PR.
Closes #1162 ~~when finished.~~
=> BLD: enhance .travis.yml with more builds and faster failing

.pep8speaks.yml, .travis.yml, odl/phantom/misc_phantoms.py
=> MAINT: add pep8speaks config file

odl/tomo/geometry/conebeam.py
Minor fix for a major issue :)
=> BUG: Fix bug with ConeFlatGeometry.__getitem__ not preserving pitch

odl/contrib/fom/test/test_supervised.py, odl/contrib/fom/test/test_unsupervised.py, odl/contrib/fom/unsupervised.py, odl/contrib/mrc/test/mrc_test.py, odl/contrib/mrc/test/uncompr_bin_test.py, odl/contrib/pytorch/test/layer.py, odl/contrib/tensorflow/test/tensorflow_test.py, odl/contrib/theano/test/theano_test.py
It's sometimes nice to get a pointwise noise estimate (e.g. with poisson noise in CT). This allows just that.
=> Add pointwise estimate noise

odl/tomo/analytic/filtered_back_projection.py
Cherry picked this, should go in ASAP, also needs a test in the long term.
Should fix #1105 as well.
=> BUG: Fix bug with parker weighting caused by new geometries

odl/solvers/util/callback.py
This is the pull request for #1174. It does exactly what I proposed in that issue.
=> Issue1174 improved callbacks

odl/solvers/nonsmooth/proximal_operators.py, odl/test/solvers/nonsmooth/proximal_operator_test.py
=> BUG: Fix bug with aliased input to l1_cconj proximal, closes #1181

odl/tomo/backends/astra_cuda.py, odl/tomo/geometry/detector.py, odl/tomo/geometry/parallel.py, odl/tomo/util/utility.py
I had about 100 test failures from master due to this, minor fixes.
Anyway, how did `np.broadcast.ndim` ever work? It doesnt seem to exist:
https://docs.scipy.org/doc/numpy/reference/generated/numpy.broadcast.html
=> Minor bugfixes

odl/trafos/fourier.py, odl/trafos/util/ft_utils.py
Once again, filtering for bad `kwargs` turned up a few issues.
=> BUG: fix FT range calculation for degenerate axes, closes #1206

odl/discr/lp_discr.py, odl/space/npy_ntuples.py, odl/space/pspace.py, odl/space/weighting.py, odl/test/space/ntuples_test.py
Just removing a whole bunch of code.
=> API: remove dist_using_inner, closes #963

odl/contrib/fom/supervised.py, odl/contrib/fom/test/test_supervised.py
Add flags to mean_squared_error, mean_absolute_error, SSIM, improve the documentation and add tests (the latter applies only to SSIM).
=> ENH: Pull request of group 1 (Workshop day, work on FOMs)

odl/contrib/datasets/README.md, odl/contrib/datasets/images/__init__.py, odl/contrib/datasets/images/cambridge.py, odl/contrib/datasets/images/examples/cambridge_images.py
Add the four images I used for the SPDHG examples to ODL.
=> Add images to odl

.gitmodules, doc/source/conf.py
This needs a force-push in the submodule first, which will change the commit hash and requires adaption of the pointer here.
=> MAINT: update numpydoc and rename folder

odl/solvers/functional/functional.py, odl/space/pspace.py
That should fix the doc failure.
=> DOC: fix broken docstring sections

odl/contrib/tensorflow/layer.py
Performance upgrades and solves my acute problem in #1270
=> PERF: Change tensorflow layer to use in place evalution

.gitignore, odl/operator/pspace_ops.py, odl/test/operator/pspace_ops_test.py
This should fix also the remaining cases.
=> BUG: fix adjoint and derivative of pspace ops, see #1290

examples/tomo/filtered_backprojection_helical_3d.py, odl/test/solvers/functional/default_functionals_test.py, odl/test/tomo/geometry/geometry_test.py, odl/tomo/geometry/conebeam.py
This is work in progress but it seems like a nice feature.
=> Add helical_geometry

odl/operator/tensor_ops.py
Can @mehrhardt check if this helps? The given code example does not work on master so it's hard for me to verify.
=> ENH: Improve runtime of PointwiseNorm, closes #1314

odl/space/fspace.py, odl/space/pspace.py, odl/test/discr/lp_discr_test.py, odl/test/space/fspace_test.py, odl/test/space/pspace_test.py
=> Is real new

odl/solvers/functional/functional.py, odl/test/solvers/functional/default_functionals_test.py, odl/test/solvers/functional/functional_test.py
=> Update the Bregman functional implementation

odl/contrib/fom/test/test_unsupervised.py, odl/contrib/fom/unsupervised.py
Increase dimension of spaces to reduce risk of random test fails.
=> TST: update tests unsupervised foms.

odl/contrib/fom/supervised.py, odl/contrib/fom/test/test_supervised.py, odl/contrib/param_opt/examples/find_optimal_parameters.py, odl/contrib/param_opt/test/test_param_opt.py
Previously I did not look carefully, so when I closed #1188 and opened #1353, I rebased on master and wanted to merge straight to master. But I do not know if there are any commits in #1280 that would then be dropped... so now I took the same commits as in #1188 (plus the two extra), and rebased on #1280.
So: which one of this and #1353 do we want to keep?
=> Newer reco pipeline

odl/contrib/tensorflow/operator.py
=> ENH: Allow TensorflowOperator to use arbitrary domain/range

odl/contrib/param_opt/param_opt.py
Probably, this has to be fixed in core ODL, too; particularly in the examples.
=> BUG: Import scipy.optimize instead of scipy.

odl/contrib/shearlab/shearlab_operator.py
I did not find a way to do this without creating a new pull request
=>  Shearlab inv adj new

odl/discr/lp_discr.py
Just implementing @kohr-h comment, this seems to solve the issue.
=> BUG: make DiscreteLpElement.show use correct interpolation, closes #1336

odl/operator/default_ops.py
=> ENH: update of error message in init for ScalingOperator.

odl/solvers/functional/default_functionals.py, odl/solvers/nonsmooth/proximal_operators.py
I needed this myself and volunteered to properly implement it in ODL. Please have a look. I think this is worth to be included. It is used for instance in blind deconvolution problems.
=> Proximal of simplex constraint

odl/contrib/README.md
=> DOC: update contrib readme with info on tests

odl/contrib/torch/operator.py, odl/contrib/torch/test/test_operator.py
Mostly due to interface changes in Pytorch.
=> Minor updates in Pytorch interface

examples/solvers/bregman_tv_tomography.py
A small Bregman-TV example in tomography.
However, I am not to convinced by the performance of the Bregman-TV algorithm on this example. Moreover, I would appreciate if anyone could double check that I have understood the idea behind iterative Bregman reconstruction correctly. Maybe @ozanoktem could have a look?
=> Bregman tv example

odl/tomo/analytic/filtered_back_projection.py
Minor change that allows us to do e.g. lambda tomography easily.
=> ENH: Allow custom function for fbp filter

odl/contrib/datasets/ct/mayo.py
It seems we had some minor (but notable in some cases) errors with the geometry descriptions.
=> BUG: Fix minor errors in mayo geometry definitions

README.md
Tiny edit, just added the newly created git repository for spdhg to README.md. I am now happy to change the spdhg contrib package any time to update to new odl syntax.
=> Add SPDHG git repository to README.md

odl/contrib/datasets/ct/mayo.py
Wouldn't you know? Yet another minor bugfix-spree for Mayo. DICOM is not fun at all.
Anyway, this should be the best version so far, and I also slightly reduced the memory redundancy.
=> ENH: Minor improvements to mayo reader

odl/solvers/functional/default_functionals.py, odl/test/solvers/functional/functional_test.py
Add `IndicatorSumConstraint` and `IndicatorSimplex` to general test suite for functionals.
Should we also add test separate in `default_functionals_test.py`?
=> Tests indicator sum and simplex

odl/contrib/param_opt/param_opt.py, odl/contrib/param_opt/test/test_param_opt.py
=> ENH: allow to pass brackets to univariate solvers

doc/source/conf.py, doc/source/dev/release.rst, doc/source/release_notes.rst
The upcoming release notes, plus a tiny change.
=> Release notes 0.7.0

setup.py
=> MAINT: add Python 3.7 to identifiers in setup.py

odl/contrib/datasets/ct/examples/mayo_reconstruct.py, odl/tomo/analytic/filtered_back_projection.py, odl/tomo/geometry/conebeam.py, odl/tomo/operators/ray_trafo.py
* Change code to follow original article
* Fix bug with default `helical_geometry`
* Rename `n_half_rot` to the more standard `n_pi`
=> MAINT: Changes to TD window

doc/source/guide/geometry_guide.rst, examples/tomo/backends/astra_performance_cuda_cone_3d_cg.py, examples/tomo/checks/check_axes_cone3d_bp.py, examples/tomo/checks/check_axes_cone3d_fp.py, examples/tomo/filtered_backprojection_cone_3d.py, examples/tomo/filtered_backprojection_cone_3d_short_scan.py, examples/tomo/ray_trafo_cone_3d.py, examples/tomo/ray_trafo_helical_cone_3d.py, odl/contrib/datasets/ct/mayo.py, odl/contrib/tomo/elekta.py, odl/test/largescale/tomo/analytic_slow_test.py, odl/test/largescale/tomo/ray_transform_slow_test.py, odl/test/tomo/backends/astra_cuda_test.py, odl/test/tomo/backends/astra_setup_test.py, odl/test/tomo/geometry/geometry_test.py, odl/test/tomo/operators/ray_trafo_test.py, odl/tomo/analytic/filtered_back_projection.py, odl/tomo/backends/astra_cuda.py, odl/tomo/geometry/conebeam.py, odl/tomo/geometry/detector.py
by analogy to CircularDetecotor and FanBeamGeometry
=>  Cylindrical and Spherical detectors added, ConeBeamGeometry created

odl/contrib/torch/operator.py
- Adapt doctests to modern PyTorch, i.e., remove `Variable` and update printing. Now they pass again.
- Make functionals work as `Module`, handy for using custom loss functions.
=> ENH: remove variable from torch doctests, make functionals work

odl/operator/default_ops.py
Another little fix that tripped me recently when trying to solve a nonlinear complex problem. We already did some other operators but missed these.
=> ENH: make some C2R operator derivatives linear

odl/solvers/functional/default_functionals.py
=> Doc: update doc for KullbackLeibler function. Closes #1218

setup.cfg
Small change that fixes #1532, in line with #1514. 
Will merge in a day or two, if no one has any comments.
=> TST: add fix for failing pytest.

odl/solvers/util/callback.py
=> Fix: increment iter in CallbackStore

doc/source/_static/custom.css, doc/source/conf.py
=> Fix for parameter formatting issue

odl/tomo/backends/astra_cpu.py, odl/tomo/backends/astra_cuda.py, odl/tomo/operators/ray_trafo.py
=> Change DiscreteLP into DiscretizedSpace in TypeError messages

odl/contrib/datasets/ct/mayo.py
See discussion in https://github.com/odlgroup/odl/commit/c332803fee2a7222e31165c24d4446d8f86a62bb#r39870655
@JevgenijaAksjonova could you check if this works for you?
=> Fix interpolation in mayo.py

odl/tomo/backends/astra_cpu.py, odl/tomo/backends/skimage_radon.py
=> Fix AttributeError in projector impl error messages

odl/contrib/tomo/elekta.py
=> Import error fixed

odl/space/base_tensors.py, odl/space/npy_tensors.py
Filed by Emilien at https://github.com/leftaroundabout/odl/pull/1
The aim is to improve readability and maintainability of ODL by sorting the classes attributes/methods/magic functions/etc in a structured way.
So far, we aim to impose this structure only on the space module.
=> Code layout/alphabetic method ordering
